CREATE TABLE Isi.Stanowisko (
	StanowiskoId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaStanowiska VARCHAR (35) NOT NULL,
	Pensja DECIMAL (9,2) DEFAULT NULL
);

CREATE TABLE Isi.Region (
	RegionId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaRegionu VARCHAR (25) DEFAULT NULL
);

CREATE TABLE Isi.Kraj (
	KrajId CHAR (2) PRIMARY KEY,
	NazwaKraju VARCHAR (40) DEFAULT NULL,
	KodWaluty VARCHAR (3) NOT NULL,
	RegionId INT NOT NULL,
	FOREIGN KEY (RegionId) REFERENCES Isi.Region (RegionId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Isi.Lokalizacja (
	LokalizacjaId INT IDENTITY(1,1) PRIMARY KEY,
	Ulica VARCHAR (40) DEFAULT NULL,
	KodPocztowy VARCHAR (12) DEFAULT NULL,
	Miasto VARCHAR (30) NOT NULL,
	KrajId CHAR (2) NOT NULL,
	FOREIGN KEY (KrajId) REFERENCES Isi.Kraj (KrajId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Isi.Oddzial (
	OddzialId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaOddzialu VARCHAR (30) NOT NULL,
	LokalizacjaId INT DEFAULT NULL,
	FOREIGN KEY (LokalizacjaId) REFERENCES Isi.Lokalizacja (LokalizacjaId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Isi.Pracownik (
	PracownikId INT IDENTITY(1,1) PRIMARY KEY,
	Imie VARCHAR (20) DEFAULT NULL,
	Nazwisko VARCHAR (25) NOT NULL,
	Adres VARCHAR(50) NOT NULL,
	Email VARCHAR (100) NOT NULL,
	Telefon VARCHAR (20) DEFAULT NULL,
	DataZatrudnienia DATE NOT NULL,
	KontoBankowe VARCHAR (40) NOT NULL,
	StanowiskoId INT NOT NULL,
	OddzialId INT DEFAULT NULL,
	FOREIGN KEY (StanowiskoId) REFERENCES Isi.Stanowisko (StanowiskoId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (OddzialId) REFERENCES Isi.Oddzial (OddzialId) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE Isi.Pracownik
DROP TABLE Isi.Oddzial
DROP TABLE Isi.Stanowisko
DROP TABLE Isi.Lokalizacja
DROP TABLE Isi.Kraj
DROP TABLE Isi.Region

SELECT * FROM Isi.Pracownik
SELECT * FROM Isi.Oddzial
SELECT * FROM Isi.Stanowisko
SELECT * FROM Isi.Lokalizacja
SELECT * FROM Isi.Kraj
SELECT * FROM Isi.Region