CREATE TABLE Isi.TypTransakcji (
	TypId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaTypu VARCHAR (35) NOT NULL
);

CREATE TABLE Isi.Waluta (
	KodId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaWaluty VARCHAR (25) NOT NULL,
	KursWymiany DECIMAL (5,2) DEFAULT NULL
);

CREATE TABLE Isi.Klient (
	KlientId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaKlienta VARCHAR (35) NOT NULL
);

CREATE TABLE Isi.Konto (
	KontoId INT IDENTITY(1,1) PRIMARY KEY,
	NazwaKonta VARCHAR (35) NOT NULL,
	NumerKonta VARCHAR (35) NOT NULL,
	Saldo DECIMAL (12, 2) NOT NULL,
	KlientId INT NOT NULL,
	FOREIGN KEY (KlientId) REFERENCES Isi.Klient (KlientId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Isi.Zlecenie (
	ZlecenieId INT IDENTITY(1,1) PRIMARY KEY,
	DataZlecenia SMALLDATETIME NOT NULL,
	LiczbaTransakcji INT NOT NULL,
	WartoscTransakcji DECIMAL (12,2) NOT NULL,
	KlientId INT NOT NULL,
	FOREIGN KEY (KlientId) REFERENCES Isi.Klient (KlientId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Isi.Transakcja (
	TransakcjaId INT IDENTITY(1,1) PRIMARY KEY,
	DataTransakcji SMALLDATETIME NOT NULL,
	NazwaOdbiorcy VARCHAR (35) NOT NULL,
	NumerKontaOdbiorcy VARCHAR (50) NOT NULL,
	Ulica VARCHAR (35) NOT NULL,
	Miasto VARCHAR (35) NOT NULL,
	KodPocztowy VARCHAR (35) NOT NULL,
	Kwota DECIMAL (12, 2) NOT NULL,
	ZlecenieId INT NOT NULL,
	TypId INT DEFAULT 1,
	KodId INT NOT NULL,
	FOREIGN KEY (ZlecenieId) REFERENCES Isi.Zlecenie (ZlecenieId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (TypId) REFERENCES Isi.TypTransakcji (TypId) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (KodId) REFERENCES Isi.Waluta (KodId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Stage.StageFI (
	StageId INT IDENTITY(1,1) PRIMARY KEY,
	DataOtrzymaniaZlecenia SMALLDATETIME DEFAULT NULL,
	Zleceniodawca VARCHAR (35) DEFAULT NULL,
	NazwaOdbiorcy VARCHAR (35) DEFAULT NULL,
	AdresOdbiorcy VARCHAR (50) DEFAULT NULL,
	NumerKontaOdbiorcy VARCHAR (50) DEFAULT NULL,
	NazwaWaluty VARCHAR (35) DEFAULT NULL,
	KwotaUSD DECIMAL (9,2) DEFAULT NULL
);

DROP TABLE Isi.Transakcja
DROP TABLE Isi.TypTransakcji
DROP TABLE Isi.Zlecenie
DROP TABLE Isi.Konto
DROP TABLE Isi.Waluta
DROP TABLE Isi.Klient
DROP TABLE Stage.StageFI

TRUNCATE TABLE Isi.Transakcja
TRUNCATE TABLE Isi.TypTransakcji
TRUNCATE TABLE Isi.Zlecenie
TRUNCATE TABLE Isi.Konto
TRUNCATE TABLE Isi.KodyWalut
TRUNCATE TABLE Isi.Klient
TRUNCATE TABLE Stage.StageFI
